export default function Head() {
  return (
    <head>
      <title>Hola</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/vercel.svg" />
    </head>
  );
}
/* favicon.ico */
